index:
    path: /
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::index' }
service_page:
    path: service
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\ServiceController::index' }
favicon:
    path: /favicon.ico
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::favicon' }
service_download:
    path: /service/download
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\ServiceController::download' }
fileserver_browse:
    path: /service/fileserver/browse
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\FileServerController::browse' }
fileserver_download:
    path: /service/fileserver/download
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\FileServerController::fileDownload' }
torchnet_browse:
    path: /service/torchnet/browse
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\TorchnetController::browse' }
torchnet_download:
    path: /service/torchnet/download
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\TorchnetController::fileDownload' }
encapsulation_page:
    path: /encapsulation
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\EncapsulationController::index' }
live:
    path: /kube/live
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::kube' }
ready:
    path: /kube/ready
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::kube' }
