index:
    path: /
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::index' }
service_page:
    path: service
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\ServiceController::index' }
favicon:
    path: /favicon.ico
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::favicon' }
service_download:
    path: /service/download
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\ServiceController::download' }
fileserver_browse:
    path: /service/fileserver/browse
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\FileServerController::browse' }
fileserver_download:
    path: /service/fileserver/download
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\FileServerController::fileDownload' }
torchnet_browse:
    path: /service/torchnet/browse
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\TorchnetController::browse' }
torchnet_download:
    path: /service/torchnet/download
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\TorchnetController::fileDownload' }
encapsulation_page:
    path: /encapsulation
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\EncapsulationController::index' }
users_list:
    path: /users
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\UserController::index' }
users_create:
    path: /users/create
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\UserController::create' }
users_edit:
    path: /users/edit
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\UserController::edit' }
users_delete:
    path: /users/delete
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\UserController::delete' }
users_setpassword:
    path: /users/setpassword
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\UserController::setPassword' }
live:
    path: /kube/live
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::kube' }
ready:
    path: /kube/ready
    defaults: { _controller: 'HomeLan\FileStore\Admin\Controller\IndexController::kube' }
