---

stages:
  - test
  - build
  
variables:
  REPO_IMAGE: registry.home-lan.co.uk/aun-filestore:react
  
phpunit_phpstan_php81:
   image: registry.home-lan.co.uk/php-81-testing:latest
   stage: test
   script:
     - cd src; composer --no-scripts install; cd ..
     - ./src/vendor/bin/phpstan analyse -n --no-ansi --no-progress src/include src/filestored --level 5

phpunit_tests_php83:
   image: registry.home-lan.co.uk/php-83-testing:latest
   stage: test
   script:
     - cd src; composer --no-scripts install; cd ..
     - mkdir coverage
     - ./src/vendor/bin/phpunit --log-junit junit.xml --coverage-xml coverage --coverage-text --colors=never
   artifacts:
     paths:
      - coverage
      - junit.xml   

phpunit_tests_php82:
   image: registry.home-lan.co.uk/php-82-testing:latest
   stage: test
   script:
     - cd src; composer --no-scripts install; cd ..
     - mkdir coverage
     - ./src/vendor/bin/phpunit --log-junit junit.xml --coverage-xml coverage --coverage-text --colors=never
   artifacts:
     paths:
      - coverage
      - junit.xml   

phpunit_tests_php81:
   image: registry.home-lan.co.uk/php-81-testing:latest
   stage: test
   script:
     - cd src; composer --no-scripts install; cd ..
     - mkdir coverage
     - ./src/vendor/bin/phpunit --log-junit junit.xml --coverage-xml coverage --coverage-text --colors=never
   artifacts:
     paths:
      - coverage
      - junit.xml   
      
container_build:
  image: 
    name: gcr.io/kaniko-project/executor:v1.22.0-debug
    entrypoint: [""]
  stage: build
   
  script:
     - echo -n "{\"auths\":{\"https://registry.home-lan.co.uk\":{\"auth\":\"$(echo -n ${DOCKER_REGISTRY_USER}:${DOCKER_REGISTRY_PW} | base64)\"}}}" > /kaniko/.docker/config.json
     - /kaniko/executor
      --context "${CI_PROJECT_DIR}"
      --dockerfile "${CI_PROJECT_DIR}/Dockerfile"
      --destination "${REPO_IMAGE}"
      --destination "${REPO_IMAGE}:latest"
      --skip-push-permission-check

