---

stages:
  - test
  - build
  
variables:
  REPO_IMAGE: registry.home-lan.co.uk/aun-filestore:react
  
phpunit_phpstan_php81:
   image: registry.home-lan.co.uk/php-81-testing:latest
   stage: test
   services:
    - docker:stable-dind
   script:
     - cd src; composer --no-scripts install; cd ..
     - ./src/vendor/bin/phpstan analyse -n --no-ansi --no-progress src/include src/filestored --level 5

phpunit_tests_php81:
   image: registry.home-lan.co.uk/php-81-testing:latest
   stage: test
   services:
    - docker:stable-dind
   script:
     - cd src; composer --no-scripts install; cd ..
     - mkdir coverage
     - ./src/vendor/bin/phpunit --log-junit junit.xml --coverage-xml coverage --coverage-text --colors=never
   artifacts:
     paths:
      - coverage
      - junit.xml   

phpunit_tests_php80:
   image: registry.home-lan.co.uk/php-80-testing:latest
   stage: test
   services:
    - docker:stable-dind
   script:
     - cd src; composer --no-scripts install; cd ..
     - ./src/vendor/bin/phpunit --log-junit junit.xml
   artifacts:
     paths:
      - junit.xml   
       
phpunit_tests_php73:
   image: registry.home-lan.co.uk/php-73-testing:latest
   stage: test
   services:
    - docker:stable-dind
   script:
     - cd src; composer --no-scripts install; cd ..
     - ./src/vendor/bin/phpunit --log-junit junit.xml
   artifacts:
     paths:
      - junit.xml   
      
phpunit_tests_php72:
   image: registry.home-lan.co.uk/php-72-testing:latest
   stage: test
   services:
    - docker:stable-dind
   script:
     - cd src; composer --no-scripts install; cd ..
     - mkdir coverage
     - ./src/vendor/bin/phpunit --log-junit junit.xml 
   artifacts:
     paths:
      - coverage
      - junit.xml   

      
container_build:
   image: docker:dind
   stage: build
   script:
     - export
     - docker login -u $DOCKER_REGISTRY_USER -p $DOCKER_REGISTRY_PW registry.home-lan.co.uk
     - docker build -t $REPO_IMAGE .
     - docker push  $REPO_IMAGE

