#!/usr/bin/php
<?php
if (file_exists(__DIR__ . '/../vendor/autoload.php')) {
    require_once __DIR__ . '/../vendor/autoload.php';
} else {
    require_once '/usr/share/aun-filestored/vendor/autoload.php';
}

use Symfony\Component\Console\Application;
use HomeLan\FileStore\Command\NewsImport;

$oApp = new Application('news-import', '1.0.0');
$oApp->addCommand(new NewsImport());
$oApp->setDefaultCommand('news-import', true);
$oApp->run();
