#!/bin/sh

#Create the default share econet to hold our virtual file root for the filestore
synoshare --get econet
if [ $? != 0 ]; then 
	//share folder does not exist 
	VOLUME=`/usr/syno/bin/servicetool --get-alive-volume`
	synoshare --add econet "" /$VOLUME/econet "" "admin,guest" "" 1 0 
fi 


