#!/usr/bin/php
<?php
if(file_exists(__DIR__."/vendor/autoload.php")){
        require_once __DIR__."/vendor/autoload.php";
}else{
        require_once "/usr/share/aun-filestored/vendor/autoload.php";
}

use HomeLan\FileStore\Console\SingleCommandApplication;
use HomeLan\FileStore\Command\EcoSyslogd;

use Monolog\Logger;
use Monolog\Handler\SyslogHandler;
use Monolog\Handler\StreamHandler;

$oLogger = new Logger("ecosyslogd");
$oLogger->pushHandler(new SyslogHandler("ecosyslogd"));
$oLogger->pushHandler(new StreamHandler('php://stdout', Logger::DEBUG));

$oApplication = new SingleCommandApplication(
	new EcoSyslogd($oLogger)
);

$oApplication->run();
