#!/usr/bin/php
<?php
require_once __DIR__."/vendor/autoload.php";

use HomeLan\FileStore\Console\SingleCommandApplication;
use HomeLan\FileStore\Command\Filestore;
use HomeLan\FileStore\Services\FileServer;
use HomeLan\FileStore\Services\PrintServer;
use HomeLan\FileStore\Services\Bridge;

use Monolog\Logger;
use Monolog\Handler\SyslogHandler;
use Monolog\Handler\StreamHandler;

$oLogger = new Logger("filestored");
$oLogger->pushHandler(new SyslogHandler("filestored"));
$oLogger->pushHandler(new StreamHandler('php://stdout', Logger::DEBUG));

$oApplication = new SingleCommandApplication(
	new Filestore(
		new FileServer($oLogger),
		new PrintServer($oLogger),
		new Bridge($oLogger),
		$oLogger
	)
);

$oApplication->run();
