#!/usr/bin/php
<?php
if(file_exists(__DIR__."/vendor/autoload.php")){
        require_once __DIR__."/vendor/autoload.php";
}else{
        require_once "/usr/share/aun-filestored/vendor/autoload.php";
}

use HomeLan\FileStore\Console\SingleCommandApplication;
use HomeLan\FileStore\Command\React;
use HomeLan\FileStore\Services\ServiceDispatcher;
use HomeLan\FileStore\Services\Provider\FileServer;
use HomeLan\FileStore\Services\Provider\PrintServer;
use HomeLan\FileStore\Services\Provider\Bridge;

use Monolog\Logger;
use Monolog\Handler\SyslogHandler;
use Monolog\Handler\StreamHandler;

$oLogger = new Logger("filestored");
$oLogger->pushHandler(new SyslogHandler("filestored"));
$oLogger->pushHandler(new StreamHandler('php://stdout', Logger::DEBUG));

if(getenv('SENTRY_URL')!==FALSE){
	echo "hi\n";
	Sentry\init(['dsn'=>getenv('SENTRY_URL'),
		'release'=>'0d74bc6a3c6211e99d450242ac110024',
		'default_integrations'=>true,
		'error_types'=>E_ERROR | E_PARSE | E_CORE_ERROR | E_CORE_WARNING | E_COMPILE_ERROR | E_COMPILE_WARNING | E_STRICT,
		'attach_stacktrace'=>true]);
}

$oApplication = new SingleCommandApplication(
	new React(
		$oLogger,
		new ServiceDispatcher(
			$oLogger,
			[
				new FileServer($oLogger),
				new PrintServer($oLogger),
				new Bridge($oLogger)
			]
		)
	)
);

$oApplication->run();
