#!/usr/bin/php
<?php
if(file_exists(__DIR__."/vendor/autoload.php")){
        require_once __DIR__."/vendor/autoload.php";
}else{
        require_once "/usr/share/aun-filestored/vendor/autoload.php";
}

use HomeLan\FileStore\Console\SingleCommandApplication;
use HomeLan\FileStore\Command\React;
use HomeLan\FileStore\Services\ServiceDispatcher;
use HomeLan\FileStore\Services\Provider\FileServer;
use HomeLan\FileStore\Services\Provider\PrintServer;
use HomeLan\FileStore\Services\Provider\Bridge;

use Monolog\Logger;
use Monolog\Handler\SyslogHandler;
use Monolog\Handler\StreamHandler;

$oLogger = new Logger("filestored");
$oLogger->pushHandler(new SyslogHandler("filestored"));
$oLogger->pushHandler(new StreamHandler('php://stdout', Logger::DEBUG));

if(getenv('SENTRY_URL')!==FALSE){
	$oLogger->info("Installed sentry debug handler (".getenv('SENTRY_URL').")");
}

$oApplication = new SingleCommandApplication(
	new React(
		$oLogger,
		ServiceDispatcher::create(
			$oLogger,
			[
				new FileServer($oLogger),
				new PrintServer($oLogger),
				new Bridge($oLogger)
			]
		)
	)
);

$oApplication->run();
